### ISSUE TITLE
crash uv_now(ts_loop)

### ISSUE THREAD

**Issue by McGonagall666** [openziti/ziti-sdk-swift#207] opened 2023-11-14 09:34 UTC
When the enrollment identity fails, continuing the enrollment will crash, which may not necessarily occur, but continuous enrollment will crash, displayed in the uv_now(ts_loop)
Has anyone encountered this problem? I have tried many methods but none have worked, including modifying the uv_loop_t Creation and destruction.
![123](https://github.com/openziti/ziti-sdk-swift/assets/61775376/538a39dc-691c-46d1-a92e-d17b3a245135)

**Comment by scareything** [comment] 2023-11-14 14:03
Hello and thanks for the report. I believe this is the same crash that is observed in #193. I have been able to reproduce this crash with ziti-tunnel-apple, but not reliably. I'll be taking a closer look this week.

**Comment by scareything** [comment] 2023-11-14 20:06
Duplicate of #193

**Closed** 2023-11-17 22:06 UTC
